### ISSUE TITLE
React 17 support?

### ISSUE THREAD

**Issue by joel-speedwell** [BeTomorrow/react-native-file-logger#21]
Hello,

It seems `react-native-file-logger` depends on `react@^16.8.1`. Is there a chance this can be updated to `react@^17.0.0` (or whichever 17 version number makes sense).

Thanks.

**Comment by punov** [comment]
If need to proceed asap,
temporary made it work with 
`npm i react-native-file-logger --legacy-peer-deps`

**Comment by alois-beto** [comment]
Fixed by 0.3.0
