### ISSUE TITLE
Plugin with id 'maven' not found

### ISSUE THREAD

**Issue by Iamivan1996** [BeTomorrow/react-native-file-logger#26]
Build failed when install this repo on latest React Native version (0.67.3),  it return two error messages

1. 
* What went wrong:
A problem occurred evaluating project ':react-native-file-logger'.
> Plugin with id 'maven' not found.

2. 
* What went wrong:
A problem occurred configuring project ':react-native-file-logger'.
> Could not find method mavenDeployer() for arguments [build_4ea9nrup07e5ggy3lwew2e09s$_run_closure4$_closure15$_closure17@30919c66] on repository container of type org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.

For temporary fix, i am just make some changes in build.gradle
About Error 1, update 
`apply plugin: 'maven'`
to
`apply plugin: 'maven-publish'`

About Error 2, comment installArchives function in build.gradle

**Comment by bmatasar** [comment]
It looks like the file build.gradle has been updated but the changes have not been published yet. Any plans to do it?

**Comment by alois-beto** [comment]
Fixed and published to npm with version 0.3.0
Sorry for the delay 🙇‍♂️
