### ISSUE TITLE
Wrong timestamp in the logs. 

### ISSUE THREAD

**Issue by aa185418** [BeTomorrow/react-native-file-logger#29]
I am writing logs at around 2:17 pm. My computer and my Android phone are both at the same time. 

However, when I write logs, I see the time in the logs as follows:

2022-04-04T18:17:51.856Z [INFO]

Can someone help me to understand which time is this? It may be taking a time from different timezone. Anyone know the fix for this?

**Comment by alois-beto** [comment]
This is because the date is in ISO format i.e. in UTC timezone.

If you want your logs in local time, feel free to use you own formatter in `FileLogger.configure()` 🙂
