### ISSUE TITLE
Android Release build empty  log file

### ISSUE THREAD

**Issue by macdonaldj** [BeTomorrow/react-native-file-logger#37]
Any reason why a release build has no log file? Debug build everything works as it should

**Comment by macdonaldj** [comment]
ouch. When sending email with log in Release build, it says "cannot attach empty file"

**Comment by alois-beto** [comment]
Sorry, I missclicked, I didn't want to close the issue 😇 

Can you provide us a reproduction code or an example app? Or any informations we can use to reproduce the bug.

**Comment by macdonaldj** [comment]
ok, let me see if the example app does the same.

**Comment by macdonaldj** [comment]
having issues getting the example app built.

`error Unable to resolve module ./App from <path>example\index.js`

**Comment by macdonaldj** [comment]
ok, this can be closed. had a babel plugin that was filtering all console logs for production

**Comment by alois-beto** [comment]
Ok, at least I could fix the example app 😄

**Comment by CYLMos** [comment]
@macdonaldj @alois-beto 

May I ask how you fix it?
I have the same issue now.

My library version is 0.4.0 and use Android 10
My configuration:
```
var RNFS = require('react-native-fs');
const logFormatter: LogFormatter = (level, msg) => {
    const now = new Date();
    const levelName = logLevelNames[level];
    return `${now.toLocaleString()} [${levelName}]  ${msg}`;
};
FileLogger.configure({
    formatter: logFormatter,
    maximumFileSize: 1024 * 1024 * 10,
    maximumNumberOfFiles: 0,
    logsDirectory: RNFS.ExternalStorageDirectoryPath + '/MyApp/Logs/'
}).then(() => { 
    // The below logs are not actually in log file
    // But they are exist with debug mode
    console.log("Start Logging - console.log");
    console.warn("Start Logging - console.warn");
    console.error("Start Logging - console.error");
    FileLogger.info("Start Logging - FIleLogger.info");
    FileLogger.warn("Start Logging - FileLogger.warn");
    FileLogger.error("Start Logging - FileLogger.error");
});
```

**Comment by macdonaldj** [comment]
@CYLMos for my case, i had a babel plugin, here were my changes

`babel.config.js`


```
-            plugins: ['transform-remove-console'],
+            "plugins": [ ["transform-remove-console", { "exclude": [ "error", "warn", "info"] }] ]
        }
```

**Comment by CYLMos** [comment]
@macdonaldj 
Thank you very much! It's working!
The difference is all the console logs I use are `console.log`.
So I should additionally add `log` into `exclude`
