### ISSUE TITLE
Fallback strategy for log file sharing

### ISSUE THREAD

**Issue by Aiosa** [BeTomorrow/react-native-file-logger#42]
Hello, firstly, thanks for this awesome library! 
I am having problems with two physical iOS devices - both use GMail instead of native apple mail system and sharing logs ends with

> Possible Unhandled Promise Rejection (id: 2):
> Error: Cannot send emails on this device

Is it possible to fix this behavior somehow? Even if it was not possible (easily), I would like a hint on what to do in such cases - the promise fails and I would like to tell the user how to share the files in a different way. I would like to avoid direct XHR post, security-wise the email sharing approach is brilliant...

Thanks

**Comment by alois-beto** [comment]
Hello,

Unfortunately the only way to send mail with attachment programmatically on iOS is to use [MFMailComposeViewController](https://developer.apple.com/documentation/messageui/mfmailcomposeviewcontroller) the default mail client. Apple does not provide any method to adapt to other mail clients (gmail for example).

Internally the lib calls the method [MFMailComposeViewController.canSendMail()](https://developer.apple.com/documentation/messageui/mfmailcomposeviewcontroller/1616879-cansendmail) and if the response if false it throws the exception `Cannot send emails on this device`.

We have some apps using this library and in this case we try/catch the call to `FileLogger.sendLogFilesByEmail()` and display a message to the user if there is an exception.

In any case you can always have access to the files directly using `FileLogger.getLogFilePaths()` and `react-native-fs` and do whatever you want with the log files.

**Comment by Aiosa** [comment]
Ok, thanks for the feedback, I guess I will tell the user for now to log-in to Mail app if it does not work for them. Sigh. What would you expect from Apple anyway. Thanks.
