### ISSUE TITLE
iOS Doesn’t support multiple recipients.

### ISSUE THREAD

**Issue by maulik54e** [BeTomorrow/react-native-file-logger#43]
in Android we are able send email  to  multiple recipients by passing value in `To` parameters  as `'xyz@gmail.com,abc@gmail.com'`
but in iOS it's only allowing  to send email to one recipient 
So if possibles add support for iOS . So we can send email to multiple recipients   

```
  const sendLogFilesByEmail = () => {
    FileLogger.sendLogFilesByEmail({
      to: 'xyz@gmail.com,abc@gmail.com',
      subject: 'Log files',
      body: 'Please find attached the log files from your app',
    });
  };
```

**Comment by alois-beto** [comment]
I added the support of passing an array of string to the `sendLogFilesByEmail` function in the `v0.4.0` version.
Working on iOS & Android of course 🙂

**Comment by maulik54e** [comment]
Thank you So much for adding that
