### ISSUE TITLE
Add log file compression feature

### ISSUE THREAD

**Issue by katzdan** [BeTomorrow/react-native-file-logger#44]
Hi, 

I love this file logger, it's so easy to use. Helped me a lot.

One great enhancement would be to email compressed log files , either a single file containing all log files or several compressed file. This would enable users to share larger log files which might be too big for email. From what I know - log/text files get compressed to about 10% of their original size.

Regards,

**Comment by alois-beto** [comment]
Hello,
Thank you for the feedback.
Our vision is to be able to view the files as easily as possible i.e. directly from the mail clients (even from a smartphone). That's why we don't use zip when sending the logs by email.
Is the size of the log files a real problem for you?

**Comment by katzdan** [comment]
Hi @alois-beto ,

Thanks for the quick response. The vision is sound and reasonable and it's completely understandable that you want a straight forward approach (and are able to implement accordingly).

My suggestion comes from my own experience developing Android apps and having to upload logs to a server for review. it follows the following :
1. In real life apps - you would want to be able to upload a log that contains everything related to the flow or bug you want to solve and sometimes this log file is larger that what you email server will let you send. zipping can greatly help sending a log sufficient for review and resolution.
2. Emailing non compressed text files are not efficient (even though they might be compressed on the transit layer). It would make sense to enable it as an option.

I'm aware that these points might not be inline with your vision. I Will still use your awesome component and will be very happy using it.

As an alternative to zipping the log files - I would suggest supporting uploading them to an Amazon S3 service - that as well might help a lot of people handle sending logs for review.

Keep on the good work!

**Comment by alois-beto** [comment]
Thank you for the detailed answer. I note the points but it is not planned in the short term to add a zip functionality for sending files by mail.
In any case the lib gives you free access to the files with `FileLogger.getLogFilePaths()` and then you can do whatever you want with them: S3, zip, etc...
