### ISSUE TITLE
Missing option to ommit the log files in mail sharing

### ISSUE THREAD

**Issue by Aiosa** [BeTomorrow/react-native-file-logger#47]
Adding such feature to the API should be a piece of cake, and it could be crucial for some people because:
 - they can reuse the module for content-related reports (i.e. wrong text there and there) as well where there is no need to include log files since such kind of mistakes could be just static content, e.g. in a database
 - various policies stress that users have options _not to_ share their data, which is the case here: it is possible to manually delete these files from the mail draft, but it would be much more elegant if developers could let the user decide whether to share their data
 - showing the option 'do not include my data' could possibly make users hesitate less to share errors, although maybe without log files - further sharing could be communicated through individually

**Comment by fdrault** [comment]
Hi,
This lib goal is to write log into files with different rollings stategies and provides them.
You can freely access to all the files path with `getLogFilePaths` and pick what you want, according to your privacy policies.

`sendLogFilesByEmail` is designed for an easy access to logs, to debug or for beta testers. It is a convenient method for developers, but it is not designed to be a bug reporting tool in production
