### ISSUE TITLE
Why logfile is not attached to the send mail functionality? [iOS]

### ISSUE THREAD

**Issue by hardikd-ajmerainfotech** [BeTomorrow/react-native-file-logger#50]
is there any way to get the log file and upload it in the mail?

**Comment by alois-beto** [comment]
This is supposed to be the normal behavior, the files should be included in the mail. 

What does the method `FileLogger.getLogFilePaths()` return? Maybe there is no file to send 🤔

**Comment by hardikd-ajmerainfotech** [comment]
The FileLogger.getLogFilePaths() method returns something like a "xyz.log" file and I am trying to send mail it will send the mail properly but not included the log file.

**Comment by alois-beto** [comment]
This is not normal but I don't have this problem on my side 😕

Do you have a reproduction scenario or a repository for me to investigate?

**Comment by hardikd-ajmerainfotech** [comment]
thanks for your reply. I finished this project.
