### ISSUE TITLE
Way to get the log file?

### ISSUE THREAD

**Issue by saravanakumarputta** [BeTomorrow/react-native-file-logger#53]
In our application we are looking for the log file to be uploaded to our logger service on demand, So, I need to get the log file and send it to the logger service via API call. Let me know if there is any method that I should look into.

**Comment by alois-beto** [comment]
The lib gives you free access to the files with `FileLogger.getLogFilePaths()` and then you can do whatever you want with them: S3, zip, etc...

**Comment by saravanakumarputta** [comment]
Awesome. Thanks for pointing it out!

**Comment by laurenzcodes** [comment]
The `getLogFilePaths` call returns an empty array even though I have checked the folder for log files and they exist. Why is this happening?
