### ISSUE TITLE
Disable a specific log level

### ISSUE THREAD

**Issue by PolarBear-H** [BeTomorrow/react-native-file-logger#54]
Hi,

I notice that in my log file, there are many long warning messasge which really disturbed me. Is it possible to disable a specific log level, like only disable loglevel.warning?

Thanks

**Comment by fdrault** [comment]
Hi, 

Logging usage is by "level", you can choose to capture all details (the default is `LogLevel.Debug`), or only the most importants.

You can't only disable `LogLevel.Warning`.
Proper usage would be to downgrade level of your disturbing warning log. 

If not possible, you can re-write the console capture by yourself

Something like this should work (not tested):
```
FileLogger.disableConsoleCapture();
const _handleLog = (level: string, msg: string) => {
	switch (level) {
		case "debug":
			FileLogger.debug(msg);
			break;
		case "log":
			FileLogger.info(msg);
			break;
		case "warning":
			// do nothing
			break;
		case "error":
			FileLogger.error(msg);
			break;
	}
};
global.__inspectorLog = _handleLog;
```
