### ISSUE TITLE
Unable to add as a dependency to an expo managed project while using expo-dev-client

### ISSUE THREAD

**Issue by 1337mus** [BeTomorrow/react-native-file-logger#55]
Hi, 

I have an expo-managed project that is using expo SDK 47 where native modules can be added to a project via [development build](https://docs.expo.dev/workflow/customizing/). 

I am getting the following error when I run it using the eas build command listed in the expo docs

```
eas build --profile development --platform ios
```

Error:
```
/node
[!] Invalid `Podfile` file: 
[!] Invalid `RNFileLogger.podspec` file: undefined method `install_modules_dependencies' for Pod:Module
Did you mean?  install_flipper_dependencies.
 #  from /Users/expo/workingdir/build/node_modules/react-native-file-logger/RNFileLogger.podspec:21
 #  -------------------------------------------
 #    ## Dependencies needed for new architecture.
 >    install_modules_dependencies(s)
 #  
 #  -------------------------------------------
.
 #  from /Users/expo/workingdir/build/packages/mobile/ios/Podfile:14
 #  -------------------------------------------
 #    use_expo_modules!
 >    config = use_native_modules!
 #  
 #  -------------------------------------------
 ```
 
Is this due to `npx pod install` being an additional step for this package to work correctly? Wouldn't react native auto linking take care of the dependent pod installations automatically?

Also does this require turbo modules to be enabled? I have it off in my project and looking at the code I am expecting it to fallback to the old NativeModule based FileLogger.

Any help is appreciated. Thanks in advance. 🙏

**Comment by fdrault** [comment]
Hi,

Thank you for reporting this issue.

Usage of `install_modules_dependencies` is the [documented way](https://reactnative.dev/docs/new-architecture-library-ios) to hide compilation options of new arch modules (dependency with RCT-Folly, Codegen etc.), while still being backward compatible
> Also does this require turbo modules to be enabled? I have it off in my project and looking at the code I am expecting it to fallback to the old NativeModule based FileLogger.

No, turbo modules is not required, react-native-file-logger should be backward compatible


> Is this due to npx pod install being an additional step for this package to work correctly? Wouldn't react native auto linking take care of the dependent pod installations automatically?

React-native still take care of auto-linking, which is 
- adding pods dependencies via CocoaPods
- adding build phase

If you enable new architecture by calling `RCT_NEW_ARCH_ENABLED=1 pod install`, this add a step:
- Call Codegen to generate TurboModules interface. This is required only with new architecture, current architecture fallback on a default interface and does not require code generation.


I don't have much expertise on Expo, so I am not sure on what broke Expo compatibility but I will look into it.
For the time being, please use the previous version

**Comment by laurenzcodes** [comment]
I get the same error in my non-expo project when trying to install this package

```
[!] Invalid `Podfile` file: 
[!] Invalid `RNFileLogger.podspec` file: undefined method `install_modules_dependencies' for Pod:Module.

 #  from /Users/x/Documents/GIT/proj-react-native/node_modules/react-native-file-logger/RNFileLogger.podspec:21
 #  -------------------------------------------
 #    ## Dependencies needed for new architecture.
 >    install_modules_dependencies(s)
 #  
 #  -------------------------------------------
.

 #  from /Users/x/Documents/GIT/proj-react-native/ios/Podfile:14
 #  -------------------------------------------
 #  
 >    config = use_native_modules!
 #  
 #  -------------------------------------------
```

**Comment by fdrault** [comment]
Hello,

It seems I have been way too ambitious by publishing the package for new architecture.
Two reasons:
- install_modules_dependencies is available only on react native 0.71
- Expo is not handling properly backward compatibility on iOS. Expo call by itself `pod install` without the flag RCT_NEW_ARCH_ENABLED, but the native code is compiled with RCT_NEW_ARCH_ENABLED
```h
#ifdef RCT_NEW_ARCH_ENABLED // is true, even if the flag is not turned on
``` 

### I rollback the release tag to version 0.4.0.
`npm install react-native-file-logger`  should now install react-native-file-logger@0.4.0

Please use this version.

For people who want to try new architecture (or are on react-native >= 0.71), you can install the next version
`npm install react-native-file-logger@next`. I will update the documentation soon.

Sorry for the inconvenience.

**Comment by willryanuk** [comment]
I'm using Expo on react-native version 0.72.3 and it fails creating a standalone build for the device... Has anyone encountered this?

❌  Undefined symbols for architecture arm64
┌─ Symbol: _OBJC_CLASS_$_MFMailComposeViewController
└─ Referenced from: objc-class-ref in RNFileLogger(FileLogger.o)


❌  ld: symbol(s) not found for architecture arm64



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)


    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-debug' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'fmt' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RCT-Folly' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-utils' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-runtimescheduler' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'ReactCommon' from project 'Pods')
    no rule to process file '/Users/willryan/Development/RapidTapping/rapid-tapping-expo-app/node_modules/react-native-agora-chat/native_src/objc/README.md' of type 'net.daringfireball.markdown' for architecture 'arm64' (in target 'react-native-chat-sdk' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-Codegen' from project 'Pods')
    Run script build phase '[CP-User] Generate app.config for prebuilt Constants.manifest' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXConstants' from project 'Pods')
    Run script build phase '[CP-User] Generate app.manifest for expo-updates' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXUpdates' from project 'Pods')
    Run script build phase 'Start Packager' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RapidTapping' from project 'RapidTapping')
    Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RapidTapping' from project 'RapidTapping')
    Run script build phase '[CP-User] [RNFB] Core Configuration' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RapidTapping' from project 'RapidTapping')

› 3 error(s), and 14 warning(s)

CommandError: Failed to build iOS project. "xcodebuild" exited with error code 65.

**Comment by fdrault** [comment]
> I'm using Expo on react-native version 0.72.3 and it fails creating a standalone build for the device... Has anyone encountered this?
> 
> ❌ Undefined symbols for architecture arm64 ┌─ Symbol: _OBJC_CLASS_$_MFMailComposeViewController └─ Referenced from: objc-class-ref in RNFileLogger(FileLogger.o)
> 
> ❌ ld: symbol(s) not found for architecture arm64
> 
> ❌ clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> ```
> Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-debug' from project 'Pods')
> Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'fmt' from project 'Pods')
> Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RCT-Folly' from project 'Pods')
> Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-utils' from project 'Pods')
> Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-runtimescheduler' from project 'Pods')
> Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'ReactCommon' from project 'Pods')
> no rule to process file '/Users/willryan/Development/RapidTapping/rapid-tapping-expo-app/node_modules/react-native-agora-chat/native_src/objc/README.md' of type 'net.daringfireball.markdown' for architecture 'arm64' (in target 'react-native-chat-sdk' from project 'Pods')
> Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-Codegen' from project 'Pods')
> Run script build phase '[CP-User] Generate app.config for prebuilt Constants.manifest' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXConstants' from project 'Pods')
> Run script build phase '[CP-User] Generate app.manifest for expo-updates' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXUpdates' from project 'Pods')
> Run script build phase 'Start Packager' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RapidTapping' from project 'RapidTapping')
> Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RapidTapping' from project 'RapidTapping')
> Run script build phase '[CP-User] [RNFB] Core Configuration' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RapidTapping' from project 'RapidTapping')
> ```
> 
> › 3 error(s), and 14 warning(s)
> 
> CommandError: Failed to build iOS project. "xcodebuild" exited with error code 65.

This seems to be a different error. Can you open a new issue so we can track this ?
