### ISSUE TITLE
TimeSpan in log file is not the same as the local time

### ISSUE THREAD

**Issue by PolarBear-H** [BeTomorrow/react-native-file-logger#58]
Hi team, is there any way to make the timespan in the logs file to aline with the local time?

**Comment by alois-beto** [comment]
Hello,
This is the default formatter:
```typescript
const defaultFormatter: LogFormatter = (level, msg) => {
	const now = new Date();
	const levelName = logLevelNames[level];
	return `${now.toISOString()} [${levelName}]  ${msg}`;
};
``` 
If the default does not suits you, you can override it in `FileLogger.configure()`

Here is the documentation of `FileLogger.configure()` :https://github.com/BeTomorrow/react-native-file-logger#fileloggerconfigureoptions-promise
