### ISSUE TITLE
FileLogger.sendLogFilesByEmail not working on iOS

### ISSUE THREAD

**Issue by yangtran093** [BeTomorrow/react-native-file-logger#60]
React native 0.72.1
iOS 16
Call FileLogger.sendLogFilesByEmail but nothing show up
Got below err from console

Bridge call to: deviceContexts
[Presentation] Attempt to present <MFMailComposeViewController: 0x15cdc4c00> on <RCTModalHostViewController: 0x146910dc0> (from <RCTModalHostViewController: 0x146910dc0>) whose view is not in the window hierarchy.
[AXRuntimeCommon] AX Lookup problem - errorCode:1100 error:Permission denied portName:'com.apple.iphone.axserver' PID:17345 (
	0   AXRuntime                           0x00000001b8ad9468 _AXGetPortFromCache + 904
	1   AXRuntime                           0x00000001b8adb5d4 AXUIElementPerformFencedActionWithValue + 768
	2   UIKit                               0x000000020ee3bd74 630A7729-DCCE-311E-B6BF-226BFFD35685 + 736628
	3   libdispatch.dylib                   0x00000001053a8028 _dispatch_call_block_and_release + 24
	4   libdispatch.dylib                   0x00000001053a9860 _dispatch_client_callout + 16
	5   libdispatch.dylib                   0x00000001053b09bc _dispatch_lane_serial_drain + 688
	6   libdispatch.dylib                   0x00000001053b1634 _dispatch_lane_invoke + 424
	7   libdispatch.dylib                   0x00000001053bd158 _dispatch_workloop_worker_thread + 696
	8   libsystem_pthread.dylib             0x00000001d97acb50 _pthread_wqthread + 284
	9   libsystem_pthread.dylib             0x00000001d97ac67c start_wqthread + 8
)
[AXRuntimeCommon] AX Lookup problem - errorCode:1100 error:Permission denied portName:'com.apple.iphone.axserver' PID:17345 (
	0   AXRuntime                           0x00000001b8ad9468 _AXGetPortFromCache + 904
	1   AXRuntime                           0x00000001b8adb5d4 AXUIElementPerformFencedActionWithValue + 768
	2   UIKit                               0x000000020ee3bd74 630A7729-DCCE-311E-B6BF-226BFFD35685 + 736628
	3   libdispatch.dylib                   0x00000001053a8028 _dispatch_call_block_and_release + 24
	4   libdispatch.dylib                   0x00000001053a9860 _dispatch_client_callout + 16
	5   libdispatch.dylib                   0x00000001053b09bc _dispatch_lane_serial_drain + 688
	6   libdispatch.dylib                   0x00000001053b1634 _dispatch_lane_invoke + 424
	7   libdispatch.dylib                   0x00000001053bd158 _dispatch_workloop_worker_thread + 696
	8   libsystem_pthread.dylib             0x00000001d97acb50 _pthread_wqthread + 284
	9   libsystem_pthread.dylib             0x00000001d97ac67c start_wqthread + 8
)

**Comment by alois-beto** [comment]
Hello,

Can you provide more details on the device used? Simulator / Real Device? Particularly if you have the default mail client installed or not.

Because not having the default iOS mail client is a known issue of the method `sendLogFilesByEmail` failing.
You can see more details here : https://github.com/BeTomorrow/react-native-file-logger/issues/42#issuecomment-1243400499

**Comment by yangtran093** [comment]
Hi @alois-beto thanks for your response
I found that when the app is showing a popup, call **sendLogFilesByEmail** will fail
