### ISSUE TITLE
Create multiple log files

### ISSUE THREAD

**Issue by sujathasperi2022** [BeTomorrow/react-native-file-logger#63]
Is it possible to write to two different log files. Say for example File A and File B. In File A I need to write only particular logs and in File B all my console and other logs. 

Any help is appreciated.
Thanks in advance.

**Comment by fdrault** [comment]
Hello,
I am sorry to say that this is not supported.
I would recommend you to put everything in the same logging system and add a discriminant, so you can filter out what you need afterwards
```
function logA(text) {
  console.log("[A] - " + text);
 }
 ```
 And then simply distinguish with commands lines:
 `grep "\[A\]" allLogs.txt > fileA.txt`
