### ISSUE TITLE
Question about console.log in src/index.ts

### ISSUE THREAD

**Issue by flaviomsb** [BeTomorrow/react-native-file-logger#65]
I've updated to `v0.5.2` and [there's a console.log on this line](https://github.com/BeTomorrow/react-native-file-logger/blob/a6dd4435c814e23d323ec9e92450def35dac8448/src/index.ts#L6) that is flooding my tests with undesirable messages. 

Is this really necessary?

**Comment by fdrault** [comment]
Hello !
You right, it is not needed.
I removed it in the last version(v0.5.3)
