### ISSUE TITLE
Invalid RNFileLogger.podspec, undefined method install_modules_dependencies for module Pod

### ISSUE THREAD

**Issue by Balaji-Burfi** [BeTomorrow/react-native-file-logger#74]
I'm facing the issue when doing pod install. I'm using react-native-file-logger version 0.5.4 I can able to understand the issue where it from. It's because of the line number 22 at package file **RNFileLogger.podspec**. I didn't use new architecture. My react native version is 0.70. If I commented the line 22 I can able to run the pod install successfully. Any one please help me to bypass that or else provide alternative way to rectify the issue.
<img width="667" alt="Screenshot 2024-06-20 at 9 31 56 PM" src="https://github.com/BeTomorrow/react-native-file-logger/assets/97144570/cbbf4aa7-68cf-4eb5-9e7c-9f9ccdf7ecae">

If I commented the marked line I can able to run the pod install. I hope it's only for new architecture but I didn't enabled the new architecture.
<img width="749" alt="Screenshot 2024-06-20 at 9 57 07 PM" src="https://github.com/BeTomorrow/react-native-file-logger/assets/97144570/5445c19e-1a5c-47c1-8c26-09bbd712b24f">

**Comment by fdrault** [comment]
Hello @Balaji-Burfi 
Thank you for your report.

The `install_modules_dependencies` method is available starting from React Native 0.71.

Therefore, my best advice is to **update to React Native 0.71** to resolve your issue.

No worries about arch, react-native-file-logger is compatible with both old **and** new architectures.
